TAB_STATE_NORMAL = 0
TAB_STATE_LOADING = 1
TAB_STATE_REVERTING = 2
TAB_STATE_SAVING = 3
TAB_STATE_PRINTING = 4
TAB_STATE_PRINT_PREVIEWING = 5
TAB_STATE_SHOWING_PRINT_PREVIEW = 6
TAB_STATE_GENERIC_NOT_EDITABLE = 7
TAB_STATE_LOADING_ERROR = 8
TAB_STATE_REVERTING_ERROR = 9
TAB_STATE_SAVING_ERROR = 10
TAB_STATE_GENERIC_ERROR = 11
TAB_STATE_CLOSING = 12
TAB_STATE_EXTERNALLY_MODIFIED_NOTIFICATION = 13
TAB_NUM_OF_STATES = 14 # This is not a valid state


WINDOW_STATE_NORMAL         = 0
WINDOW_STATE_SAVING         = 1 << 1
WINDOW_STATE_PRINTING       = 1 << 2
WINDOW_STATE_LOADING        = 1 << 3
WINDOW_STATE_ERROR          = 1 << 4
WINDOW_STATE_SAVING_SESSION = 1 << 5
